server:
  port: 8081

spring:
  profiles:
    active: dev
  jackson:
    serialization:
      indent-output: true

#to expose all endpoints of the actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"

---

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:spring-rest-api
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  config:
    activate:
      on-profile: dev

---

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring-rest-api-qa
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    activate:
      on-profile: qa

---

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring-rest-api
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    activate:
      on-profile: prod